# Generated by Django 4.2.20 on 2025-04-14 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_scanner', '0002_customuser_address_customuser_dob_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogenqr',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='auto_gen_qrcode/'),
        ),
        migrations.CreateModel(
            name='LoginRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
