# Generated by Django 4.2.20 on 2025-04-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_scanner', '0003_alter_autogenqr_qr_code_loginregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginregister',
            name='date',
        ),
        migrations.AddField(
            model_name='loginregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
