# Generated by Django 4.2.20 on 2025-04-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_scanner', '0004_remove_loginregister_date_loginregister_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode2',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qrcode2',
            name='person_image',
            field=models.ImageField(blank=True, null=True, upload_to='person_image/'),
        ),
    ]
