# Generated by Django 4.2.20 on 2025-04-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_scanner', '0006_autogenqr_location_autogenqr_person_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode2',
            name='location',
        ),
        migrations.RemoveField(
            model_name='qrcode2',
            name='person_image',
        ),
    ]
